Feature/apple watch ecg
cph-cachet/flutter-plugins pull request #320
Opened 2021-03-31 17:29 UTC by claytoncasey01

@ZuSe Had to create a new pull request for some reason. Conflicts should be fixed now.

2021-04-01 21:29 UTC, ZuSe commented
looks good, thanks!

2021-04-01 21:29 UTC, ZuSe approved these changes

2021-04-05 20:06 UTC, claytoncasey01 commented
@ZuSe Had to resolve some conflicts, those are fixed up now and good to merge after a review.

2021-04-12 14:08 UTC, denkoul commented
What is the status of this? I am a big fan of your package and I am waiting for this feature. Thanks

2021-04-13 21:41 UTC, ZuSe requested changes
Use strong types wherever possible

2021-04-13 21:41 UTC, ZuSe commented on packages/health/lib/src/health_data_point.dart
> +  List _values;
Can you type it?

2021-04-21 11:05 UTC, claytoncasey01 commented on packages/health/lib/src/health_data_point.dart
> +  List _values;
Yeah I will get that done ASAP

2021-07-07 07:31 UTC, Moseco commented
Is this PR still being worked on?

@claytoncasey01

2021-07-16 16:36 UTC, claytoncasey01 commented
> Is this PR still being worked on?
> 
> @claytoncasey01

Sorry I haven't had any time to continue working on this. I did it for a specific need for our company and may not be useful to anyone else. So we work with Hospitals who have access to recreate ECG from the voltage data, this change only returns an array of Voltage from the leads and time. If this is useful I can try to get that finished but you will not get any events, just an array of voltages.

2022-08-28 11:11 UTC, closed without merging